apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        env:
        - name: HTTP_PORT
          valueFrom:
            configMapKeyRef:
              name: myconfigmap
              key: mtport
        ports:
        - containerPort: 8081
      - name: nginx
        image: nginx
        volumeMounts:
        - mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
          name: myweb

        ports:
        - containerPort: 80
      volumes:
      - name: myweb
        configMap:
          name: myconfigmap

---
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    app: myapp
  ports:
  - name: web
    port: 80
    targetPort: 80
  - name: multitool
    port: 8081
    targetPort: 8081
